# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ot_simulator/mqtt_bronze.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# Version check disabled for Databricks Apps compatibility
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     6,
#     31,
#     1,
#     '',
#     'ot_simulator/mqtt_bronze.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eot_simulator/mqtt_bronze.proto\x12\x04mqtt\"\xba\x02\n\x10MQTTBronzeRecord\x12\x12\n\nevent_time\x18\x01 \x01(\x03\x12\x13\n\x0bingest_time\x18\x02 \x01(\x03\x12\x13\n\x0bsource_name\x18\x03 \x01(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x10\n\x08industry\x18\x05 \x01(\t\x12\x13\n\x0bsensor_name\x18\x06 \x01(\t\x12\r\n\x05value\x18\x07 \x01(\x01\x12\x14\n\x0cvalue_string\x18\x08 \x01(\t\x12\x0c\n\x04unit\x18\t \x01(\t\x12\x13\n\x0bsensor_type\x18\n \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x0b \x01(\x03\x12\x0b\n\x03qos\x18\x0c \x01(\x05\x12\x0e\n\x06retain\x18\r \x01(\x08\x12\x10\n\x08plc_name\x18\x0e \x01(\t\x12\x12\n\nplc_vendor\x18\x0f \x01(\t\x12\x11\n\tplc_model\x18\x10 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ot_simulator.mqtt_bronze_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MQTTBRONZERECORD']._serialized_start=41
  _globals['_MQTTBRONZERECORD']._serialized_end=355
# @@protoc_insertion_point(module_scope)
